-- ============================================================
--  Puerto Habana — Migración v2
--  1. Agregar 'dev' al CHECK constraint de usuarios.rol
--  2. Crear tabla tareas para lavaplatos
-- ============================================================

-- ── 1. Agregar 'dev' a los roles permitidos ────────────────────────────────
-- Primero, dropear por nombre conocido (por si ya se ejecutó antes)
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_rol_check;

-- Luego buscar y dropear cualquier constraint viejo con nombre auto-generado
DO $$
DECLARE
  v_conname TEXT;
BEGIN
  SELECT con.conname INTO v_conname
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'usuarios'
    AND con.contype = 'c'
    AND con.conname != 'usuarios_rol_check'
    AND pg_get_constraintdef(con.oid) ~* '(^|\s)rol(\s|$)';
    
  IF v_conname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE usuarios DROP CONSTRAINT %I', v_conname);
    RAISE NOTICE 'Dropped old constraint: %', v_conname;
  END IF;
END $$;

-- Crear el nuevo constraint incluyendo 'dev'
ALTER TABLE usuarios ADD CONSTRAINT usuarios_rol_check 
  CHECK (rol IN ('admin','mozo','cocina','ayudante_cocina','lavaplato','dev'));

-- ── 2. Tabla de tareas para lavaplatos ────────────────────────────────────
CREATE TABLE IF NOT EXISTS tareas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  asignado_a UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  creado_por UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  estado TEXT NOT NULL CHECK (estado IN ('pendiente','completada')) DEFAULT 'pendiente',
  fecha_limite DATE,
  completada_en TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Activar Realtime para tareas
ALTER PUBLICATION supabase_realtime ADD TABLE tareas;

-- ── 3. Agregar telefono, turno y area a usuarios (si no existen) ──────────
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS telefono TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS turno TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS fecha_ingreso DATE;
