-- ============================================================
--  NOTAS — Bloc de Notas Inteligente
--  Reemplaza la sección Gastos por un sistema de notas con
--  tags detectables: [Gasto], [Cocina], [Bebidas], [Insumos]
-- ============================================================

CREATE TABLE IF NOT EXISTS notas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contenido TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  monto NUMERIC(10,2),
  usuario_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Agregar a realtime para notificaciones en vivo
ALTER PUBLICATION supabase_realtime ADD TABLE notas;

-- Migrar gastos existentes como notas con tag 'gasto'
INSERT INTO notas (contenido, tags, monto, created_at)
SELECT
  descripcion,
  ARRAY['gasto'],
  monto,
  created_at
FROM gastos
WHERE NOT EXISTS (SELECT 1 FROM notas LIMIT 1);
