-- ============================================================
--  Puerto Habana — Migración v3
--  Inventario mejorado: códigos de barra, imágenes, tamaños,
--  costo, historial de movimientos y alertas
-- ============================================================

-- ── 1. Nuevas columnas para inventario ──────────────────────
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS codigo_barras TEXT;
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS imagen_url TEXT;
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS costo NUMERIC(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS tamanos JSONB;

-- ── 2. Tabla de movimientos de inventario ───────────────────
CREATE TABLE IF NOT EXISTS inventario_movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventario_id BIGINT NOT NULL REFERENCES inventario(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('entrada','salida','ajuste')) DEFAULT 'entrada',
  cantidad INTEGER NOT NULL,
  stock_anterior INTEGER NOT NULL DEFAULT 0,
  stock_nuevo INTEGER NOT NULL DEFAULT 0,
  referencia TEXT,
  referencia_id TEXT,
  notas TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_inventario_movimientos_item ON inventario_movimientos(inventario_id);
CREATE INDEX IF NOT EXISTS idx_inventario_movimientos_fecha ON inventario_movimientos(created_at DESC);

-- ── 3. Activar Realtime para la nueva tabla ─────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE inventario_movimientos;

-- ── 4. Actualizar seed con datos de ejemplo ─────────────────
UPDATE inventario SET
  codigo_barras = CASE nombre
    WHEN 'Cerveza Pilsner' THEN '7750101001000'
    WHEN 'Inca Kola'       THEN '7750101010101'
    WHEN 'Chicha Morada'   THEN '7750101020202'
    WHEN 'Jugo de Naranja' THEN '7750101030303'
    ELSE NULL
  END,
  costo = CASE nombre
    WHEN 'Cerveza Pilsner' THEN 6.00
    WHEN 'Inca Kola'       THEN 2.50
    WHEN 'Chicha Morada'   THEN 3.50
    WHEN 'Jugo de Naranja' THEN 3.00
    WHEN 'Ceviche de Pescado'  THEN 22.00
    WHEN 'Ceviche Mixto'       THEN 24.00
    WHEN 'Arroz con Mariscos'  THEN 19.00
    WHEN 'Lomo Saltado'        THEN 16.00
    WHEN 'Jalea Mixta'         THEN 20.00
    WHEN 'Leche de Tigre'      THEN 10.00
    WHEN 'Taper Grande'        THEN 1.20
    WHEN 'Taper Mediano'       THEN 0.80
    WHEN 'Bolsa Kraft'         THEN 0.40
    ELSE 0
  END,
  tamanos = CASE 
    WHEN nombre = 'Cerveza Pilsner' THEN '[{"nombre":"Botella 355ml","precio":12,"costo":6},{"nombre":"Botella 1L","precio":20,"costo":10}]'::jsonb
    WHEN nombre = 'Inca Kola'       THEN '[{"nombre":"Botella 500ml","precio":5,"costo":2.5},{"nombre":"Botella 1L","precio":8,"costo":4},{"nombre":"Botella 3L","precio":15,"costo":7}]'::jsonb
    WHEN nombre = 'Chicha Morada'   THEN '[{"nombre":"Vaso 400ml","precio":8,"costo":3.5},{"nombre":"Jarra 1L","precio":15,"costo":7}]'::jsonb
    WHEN nombre = 'Jugo de Naranja' THEN '[{"nombre":"Vaso 400ml","precio":8,"costo":3},{"nombre":"Jarra 1L","precio":15,"costo":6}]'::jsonb
    ELSE NULL
  END
WHERE seccion IN ('bebidas', 'comida', 'tapers');
