-- ============================================================
--  Puerto Habana — Migración v4
--  Clientes, Promociones, Boletas Electrónicas, WhatsApp
-- ============================================================

-- ── 1. TABLA CLIENTES ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  dni TEXT,
  ruc TEXT,
  telefono TEXT,
  email TEXT,
  direccion TEXT,
  notas TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Índices para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_clientes_dni ON clientes(dni);
CREATE INDEX IF NOT EXISTS idx_clientes_ruc ON clientes(ruc);
CREATE INDEX IF NOT EXISTS idx_clientes_telefono ON clientes(telefono);


-- ── 2. TABLA PROMOCIONES ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS promociones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'general' CHECK (tipo IN ('general','descuento','combo','2x1','otro')),
  descuento_porcentaje NUMERIC(5,2),
  fecha_inicio TIMESTAMP WITH TIME ZONE,
  fecha_fin TIMESTAMP WITH TIME ZONE,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  imagen_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);


-- ── 3. TABLA ENVÍOS WHATSAPP (historial de envíos masivos) ────
CREATE TABLE IF NOT EXISTS envios_whatsapp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promocion_id BIGINT REFERENCES promociones(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('promocion','boleta','voucher','personalizado')),
  mensaje TEXT NOT NULL,
  total_destinatarios INTEGER NOT NULL DEFAULT 0,
  enviados INTEGER NOT NULL DEFAULT 0,
  fallidos INTEGER NOT NULL DEFAULT 0,
  programado_para TIMESTAMP WITH TIME ZONE,
  enviado_en TIMESTAMP WITH TIME ZONE,
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','enviando','completado','parcial','fallido')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);


-- ── 4. TABLA DESTINATARIOS DE ENVÍO ───────────────────────────
CREATE TABLE IF NOT EXISTS envios_destinatarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id BIGINT NOT NULL REFERENCES envios_whatsapp(id) ON DELETE CASCADE,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
  telefono TEXT NOT NULL,
  nombre TEXT,
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','enviado','fallido')),
  error TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_envios_destinatarios_envio ON envios_destinatarios(envio_id);


-- ── 5. TABLA BOLETAS ELECTRÓNICAS ─────────────────────────────
CREATE TABLE IF NOT EXISTS boletas_electronicas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comanda_id BIGINT REFERENCES comandas(id) ON DELETE SET NULL,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
  tipo_doc TEXT NOT NULL CHECK (tipo_doc IN ('boleta','factura')) DEFAULT 'boleta',
  numero_doc TEXT,
  razon_social TEXT,
  direccion TEXT,
  total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  igv NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  xml_enviado TEXT,
  respuesta_sunat JSONB,
  estado_sunat TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado_sunat IN ('pendiente','enviado','aceptado','rechazado','baja')),
  nubefact_id TEXT,
  serie TEXT,
  numero TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_boletas_electronicas_comanda ON boletas_electronicas(comanda_id);
CREATE INDEX IF NOT EXISTS idx_boletas_electronicas_cliente ON boletas_electronicas(cliente_id);


-- ── Agregar campo boleta_electronica_ids a comandas ────────────
ALTER TABLE comandas ADD COLUMN IF NOT EXISTS boleta_electronica_ids BIGINT[];
