-- ============================================================
--  Puerto Habana Cevicheria — Esquema para Supabase (PostgreSQL)
--  Copia y pega este contenido en el SQL Editor de Supabase
-- ============================================================

-- ── USUARIOS / PERSONAL ───────────────────────────────────────────────────────
CREATE TABLE usuarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL,
  email TEXT UNIQUE,
  dni TEXT,
  rol TEXT NOT NULL CHECK (rol IN ('admin','mozo','cocina','ayudante_cocina','lavaplato')) DEFAULT 'mozo',
  salario_monto NUMERIC(10,2),
  salario_tipo TEXT CHECK (salario_tipo IN ('diario','semanal','mensual')),
  foto_url TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── MESAS ─────────────────────────────────────────────────────────────────────
CREATE TABLE mesas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  sillas INTEGER NOT NULL DEFAULT 4,
  estado TEXT NOT NULL CHECK (estado IN ('disponible','ocupada','reservada')) DEFAULT 'disponible',
  unida_con JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── RESERVAS ──────────────────────────────────────────────────────────────────
CREATE TABLE reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id BIGINT REFERENCES mesas(id) ON DELETE SET NULL,
  cliente TEXT NOT NULL,
  telefono TEXT,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  personas INTEGER NOT NULL DEFAULT 2,
  notas TEXT,
  estado TEXT NOT NULL CHECK (estado IN ('pendiente','confirmada','cancelada','completada')) DEFAULT 'pendiente',
  mozo_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── COMANDAS ──────────────────────────────────────────────────────────────────
CREATE TABLE comandas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id BIGINT REFERENCES mesas(id) ON DELETE SET NULL,
  mesa_nombre TEXT NOT NULL,
  mozo_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  mozo_nombre TEXT,
  estado TEXT NOT NULL CHECK (estado IN ('Pendiente','Preparando','Listo','Entregado','Cancelado')) DEFAULT 'Pendiente',
  total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fecha DATE NOT NULL,
  hora TEXT NOT NULL,
  notas TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── ITEMS DE COMANDA ──────────────────────────────────────────────────────────
CREATE TABLE comanda_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comanda_id BIGINT NOT NULL REFERENCES comandas(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  cantidad INTEGER NOT NULL DEFAULT 1,
  precio NUMERIC(10,2) NOT NULL,
  categoria TEXT NOT NULL CHECK (categoria IN ('comida','bebidas')) DEFAULT 'comida',
  notas TEXT,
  estado TEXT NOT NULL CHECK (estado IN ('Pendiente','Preparando','Listo','Entregado')) DEFAULT 'Pendiente',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── INVENTARIO ────────────────────────────────────────────────────────────────
CREATE TABLE inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seccion TEXT NOT NULL CHECK (seccion IN ('comida','bebidas','tapers','insumos')) DEFAULT 'comida',
  nombre TEXT NOT NULL,
  categoria TEXT,
  tipo TEXT,
  precio NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  cantidad INTEGER NOT NULL DEFAULT 0,
  unidad TEXT NOT NULL DEFAULT 'unidad',
  minimo INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── GASTOS ────────────────────────────────────────────────────────────────────
CREATE TABLE gastos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL,
  categoria TEXT NOT NULL DEFAULT 'Otros',
  monto NUMERIC(10,2) NOT NULL,
  fecha DATE NOT NULL,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── PAGOS A PERSONAL ──────────────────────────────────────────────────────────
CREATE TABLE pagos_personal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  nombre TEXT NOT NULL,
  monto NUMERIC(10,2) NOT NULL,
  concepto TEXT NOT NULL DEFAULT 'Pago Jornal',
  fecha DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── MERMAS / DESPERDICIOS ─────────────────────────────────────────────────────
CREATE TABLE mermas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL,
  costo NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fecha DATE NOT NULL,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── VENTAS DIARIAS ────────────────────────────────────────────────────────────
CREATE TABLE ventas_diarias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE UNIQUE NOT NULL,
  total_comandas INTEGER NOT NULL DEFAULT 0,
  total_ingresos NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_comida NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_bebidas NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── CONFIGURACION ─────────────────────────────────────────────────────────────
CREATE TABLE configuracion (
  clave TEXT PRIMARY KEY,
  valor TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ============================================================
--  DATOS INICIALES (SEED)
-- ============================================================

INSERT INTO mesas (id, nombre, sillas) VALUES
  (1,'Mesa 1',4),(2,'Mesa 2',4),(3,'Mesa 3',4),(4,'Mesa 4',4),
  (5,'Mesa 5',4),(6,'Mesa 6',6),(7,'Mesa 7',6),(8,'Mesa 8',2);

INSERT INTO inventario (seccion, nombre, categoria, precio, cantidad, unidad, minimo) VALUES
  ('comida', 'Ceviche de Pescado', 'Ceviches',       42.00, 20,'plato',   5),
  ('comida', 'Ceviche Mixto',      'Ceviches',       45.00, 15,'plato',   5),
  ('comida', 'Arroz con Mariscos', 'Platos Fuertes', 38.00, 18,'plato',   5),
  ('comida', 'Lomo Saltado',       'Platos Fuertes', 32.00, 12,'plato',   5),
  ('comida', 'Jalea Mixta',        'Platos Fuertes', 40.00, 10,'plato',   5),
  ('comida', 'Leche de Tigre',     'Entradas',       20.00, 25,'plato',   5),
  ('bebidas','Cerveza Pilsner',    'Cervezas',       12.00, 48,'botella',10),
  ('bebidas','Inca Kola',          'Refrescos',       5.00, 36,'botella',10),
  ('bebidas','Chicha Morada',      'Jugos',           8.00, 20,'vaso',    5),
  ('bebidas','Jugo de Naranja',    'Jugos',           8.00, 15,'vaso',    5),
  ('tapers', 'Taper Grande',       'Envase',          2.50,100,'unidad', 20),
  ('tapers', 'Taper Mediano',      'Envase',          1.50,150,'unidad', 20),
  ('tapers', 'Bolsa Kraft',        'Empaque',         0.80,200,'unidad', 30);

INSERT INTO configuracion (clave, valor) VALUES
  ('nombreEmpresa','Puerto Habana Cevicheria'),
  ('direccion',    'Av. Colonización 1115'),
  ('telefono',     '+51 123 456 789'),
  ('email',        'contacto@puertohabana.com'),
  ('horarioMañana','09:00 - 14:00'),
  ('horarioTarde', '15:00 - 23:00'),
  ('sidebarDesign','normal'),
  ('navbarStyle',  'original'),
  ('ruc',          '10429025546');

-- ============================================================
-- FUNCIÓN UPSERT VENTAS DIARIAS (la llama /api/pedidos)
-- ============================================================
CREATE OR REPLACE FUNCTION upsert_ventas_diarias(
  p_fecha DATE,
  p_ingresos NUMERIC,
  p_comida NUMERIC,
  p_bebidas NUMERIC
) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO ventas_diarias (fecha, total_comandas, total_ingresos, total_comida, total_bebidas)
  VALUES (p_fecha, 1, p_ingresos, p_comida, p_bebidas)
  ON CONFLICT (fecha) DO UPDATE
    SET total_comandas = ventas_diarias.total_comandas + 1,
        total_ingresos = ventas_diarias.total_ingresos + EXCLUDED.total_ingresos,
        total_comida   = ventas_diarias.total_comida   + EXCLUDED.total_comida,
        total_bebidas  = ventas_diarias.total_bebidas  + EXCLUDED.total_bebidas,
        updated_at     = now();
END;
$$;

-- ============================================================
-- ACTIVAR REALTIME PARA TODAS LAS TABLAS
-- ============================================================
alter publication supabase_realtime add table usuarios;
alter publication supabase_realtime add table mesas;
alter publication supabase_realtime add table comandas;
alter publication supabase_realtime add table comanda_items;
alter publication supabase_realtime add table inventario;
alter publication supabase_realtime add table reservas;

-- ============================================================
-- ACTUALIZACIÓN: NOTIFICACIONES Y METODOS DE PAGO (YAPE/EFECTIVO)
-- ============================================================

-- 1. Agregar métodos de pago a comandas
ALTER TABLE comandas
ADD COLUMN IF NOT EXISTS metodo_pago TEXT NOT NULL CHECK (metodo_pago IN ('Efectivo','Yape','Tarjeta','Otro')) DEFAULT 'Efectivo';

-- 2. Agregar el registro de Yape y Efectivo al resumen de ventas diarias
ALTER TABLE ventas_diarias
ADD COLUMN IF NOT EXISTS total_yape NUMERIC(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS total_efectivo NUMERIC(10,2) NOT NULL DEFAULT 0.00;

-- 3. Crear la nueva tabla de notificaciones
CREATE TABLE IF NOT EXISTS notificaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  rol_destino TEXT,
  titulo TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  leida BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Agregar la tabla notificaciones a realtime
ALTER PUBLICATION supabase_realtime ADD TABLE notificaciones;

-- ============================================================
--  ASISTENCIA DEL PERSONAL
-- ============================================================
CREATE TABLE IF NOT EXISTS asistencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  fecha DATE NOT NULL,
  hora_llegada TIME NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  CONSTRAINT unique_asistencia_dia UNIQUE (usuario_id, fecha)
);

ALTER PUBLICATION supabase_realtime ADD TABLE asistencia;

-- ============================================================
--  SUSCRIPCIONES PUSH (notificaciones nativas)
-- ============================================================
CREATE TABLE IF NOT EXISTS suscripciones_push (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  rol TEXT,
  subscription JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

ALTER PUBLICATION supabase_realtime ADD TABLE suscripciones_push;
